version: '2'

services:
  db:
    image: mysql:5.7
    container_name: omeka_db
    restart: always
    networks:
      network1:
        ipv4_address: 172.28.1.3
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: socialarchive
      MYSQL_USER: omekas
      MYSQL_PASSWORD: omekasPass

  omeka:
    depends_on:
      - db
    build:
      context: .
    container_name: omekas
    restart: always
    ports:
      - '80:80'
    networks:
      network1:
        ipv4_address: 172.28.1.2
    links:
      - db:db
    volumes:
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
      - omeka:/var/www/html/volume

volumes:
  db:
  omeka:
  /var/run/mysqld/mysqld.sock:

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
