version: '2'

services:
  db:
    image: mysql:5.7
    container_name: omeka_db
    restart: always
    networks:
      - network1
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: very_difficult_password_1
      MYSQL_DATABASE: long_string_1
      MYSQL_USER: long_string_2
      MYSQL_PASSWORD: very_difficult_password_2

  omeka:
    depends_on:
      - db
    build:
      context: .
    container_name: omekas
    restart: always
    networks:
      - network1
    links:
      - db:db
    volumes:
      - omeka:/var/www/html/volume
    labels:
      - 'traefik.backend=omeka'
      - 'traefik.frontend.rule=Host:indiasocialarchive.iiit.ac.in'

  traefik:
    image: traefik:latest
    restart: always
    networks:
      - network1
    command: --web --docker --docker.domain=indiasocialarchive.iiit.ac.in
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

volumes:
  db:
  omeka:

networks:
  network1:
